import type { Metadata } from "next";
import { Geist, Geist_Mono, Work_Sans } from "next/font/google";
import "./globals.css";

// Configure the font
const workSans = Work_Sans({
  subsets: ["latin"], // Specify the character subsets (e.g., 'latin')
  weight: ["300", "400", "700"], // Specify the weights you need (e.g., regular and bold)
  variable: "--font-work-sans", // Optional: Define a CSS variable for the font
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cloud Camilon | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${workSans.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
